// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package java

import (
	"bufio"
	"errors"
	"io"
	"log/slog"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"syscall"

	"github.com/googleapis/librarian/internal/config"
)

const (
	autoGeneratedMarker     = "// AUTO-GENERATED DOCUMENTATION AND CLASS."
	autoGeneratedAnnotation = "@Generated(\"by gapic-generator-java\")"
	protobufMarker          = "// Generated by the protocol buffer compiler.  DO NOT EDIT!"
	grpcMarker              = "@io.grpc.stub.annotations.GrpcGenerated"
)

var (
	itTestRegexp          = regexp.MustCompile(`src/test/java/com/google/cloud/.*/v.*/it/IT.*Test\.java$`)
	versionRegexp         = regexp.MustCompile(`src/main/java/com/google/.*/v.*/stub/Version\.java$`)
	generatedNonJavaFiles = []string{
		"gapic_metadata.json",
		"reflect-config.json",
	}
	// generateIfMissingFiles are files that are manually maintained after creation. Bypass in clean.
	generateIfMissingFiles = []string{
		"clirr-ignored-differences.xml",
		"pom.xml",
	}
)

// Clean removes files in the library's output directory that are not in the keep list.
// It targets patterns like proto-*, grpc-*, and the main GAPIC module.
func Clean(library *config.Library) error {
	patterns := cleanPatterns(library)
	slog.Debug("Clean patterns", "output", library.Output, "patterns", patterns)
	keepSet := newKeepSet(library.Keep)
	for pattern, useMarker := range patterns {
		matches, err := filepath.Glob(filepath.Join(library.Output, pattern))
		if err != nil {
			return err
		}
		for _, match := range matches {
			if err := cleanPath(match, library.Output, keepSet, useMarker); err != nil {
				return err
			}
		}
	}
	return nil
}

// cleanPatterns returns a map of directory patterns to be cleaned.
// The key is the path pattern relative to the library output directory.
// The boolean value indicates whether marker-based cleaning should be used:
//   - true: Enable marker-based cleaning. Only .java files containing auto-generation
//     markers are deleted. Used for GAPIC source directories to protect manual edits.
//   - false: Disable marker-based cleaning. Files are deleted unconditionally
//     (subject to general preservation rules). Used for Proto, GRPC, and samples.
func cleanPatterns(library *config.Library) map[string]bool {
	libraryCoordinates := DeriveLibraryCoordinates(library)
	patterns := map[string]bool{
		filepath.Join("samples", "snippets", "generated"): false,
		".repo-metadata.json":                             false,
	}
	for _, api := range library.APIs {
		javaAPI := api.Java
		if javaAPI == nil {
			javaAPI = &config.JavaAPI{}
		}
		version := filepath.Base(api.Path)
		apiCoordinates := DeriveAPICoordinates(libraryCoordinates, version, javaAPI)
		if apiCoordinates.Proto.ArtifactID != "" && shouldGenerateProto(javaAPI) {
			patterns[filepath.Join(apiCoordinates.Proto.ArtifactID, "src")] = false
		}
		if apiCoordinates.GRPC.ArtifactID != "" && shouldGenerateGRPC(javaAPI) {
			patterns[filepath.Join(apiCoordinates.GRPC.ArtifactID, "src")] = false
		}
		if apiCoordinates.GAPIC.ArtifactID != "" && shouldGenerateGAPIC(javaAPI) {
			patterns[filepath.Join(apiCoordinates.GAPIC.ArtifactID, "src")] = true
		}
	}
	return patterns
}

func cleanPath(targetPath, root string, keepSet map[string]bool, useMarker bool) error {
	var dirs []string
	err := filepath.WalkDir(targetPath, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			rel, err := filepath.Rel(root, path)
			if err != nil {
				return err
			}
			if keepSet[filepath.ToSlash(rel)] {
				return filepath.SkipDir
			}
			dirs = append(dirs, path)
			return nil
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		relSlash := filepath.ToSlash(rel)
		if shouldPreserve(relSlash, keepSet) {
			return nil
		}
		if slices.Contains(generateIfMissingFiles, d.Name()) {
			return nil
		}
		if useMarker {
			shouldClean, err := shouldCleanMarkerPath(path, d)
			if err != nil {
				return err
			}
			if !shouldClean {
				return nil
			}
		}
		slog.Info("Deleting path", "path", path)
		return os.Remove(path)
	})
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return err
	}
	// Remove empty directories in reverse order (bottom-up).
	for i := len(dirs) - 1; i >= 0; i-- {
		d := dirs[i]
		rel, err := filepath.Rel(root, d)
		if err != nil {
			return err
		}
		if !keepSet[filepath.ToSlash(rel)] {
			if err := os.Remove(d); err != nil && !errors.Is(err, fs.ErrNotExist) && !isDirNotEmpty(err) {
				return err
			}
		}
	}
	return nil
}

// isDirNotEmpty returns true if err indicates the directory is not empty.
func isDirNotEmpty(err error) bool {
	return errors.Is(err, syscall.ENOTEMPTY) || errors.Is(err, syscall.EEXIST)
}

// newKeepSet normalizes a list of keep paths using [path.Clean] and returns
// a map for fast lookup.
func newKeepSet(keep []string) map[string]bool {
	keepSet := make(map[string]bool)
	for _, k := range keep {
		normalized := path.Clean(filepath.ToSlash(k))
		if normalized == "." {
			continue
		}
		keepSet[strings.TrimSuffix(normalized, "/")] = true
	}
	return keepSet
}

// isKept returns true if the path is explicitly kept by the user.
func isKept(p string, keepSet map[string]bool) bool {
	cleanP := path.Clean(p)
	if keepSet[cleanP] {
		return true
	}

	dir := path.Dir(cleanP)
	for dir != "." && dir != "/" && dir != "" {
		if keepSet[dir] {
			return true
		}
		dir = path.Dir(dir)
	}
	return false
}

// shouldPreserve returns true if the given slash-separated path should be preserved
// based on the keepSet or standard preservation patterns.
// It also checks if any ancestor directory is in the keepSet.
func shouldPreserve(p string, keepSet map[string]bool) bool {
	return isKept(p, keepSet) || isDefaultPreserved(p)
}

func isDefaultPreserved(path string) bool {
	return itTestRegexp.MatchString(path) || versionRegexp.MatchString(path)
}

// isManualFile checks if the file at the given path is manually maintained.
func isManualFile(path string, name string) (bool, error) {
	if slices.Contains(generatedNonJavaFiles, name) {
		return false, nil
	}
	if filepath.Ext(path) != ".java" {
		return true, nil
	}
	hasGenMarker, err := hasMarker(path)
	if err != nil {
		return false, err
	}
	return !hasGenMarker, nil
}

// shouldCleanMarkerPath returns true if the file at path should be cleaned based on
// its name or whether it contains the auto-generated marker.
func shouldCleanMarkerPath(path string, d os.DirEntry) (bool, error) {
	isManual, err := isManualFile(path, d.Name())
	if err != nil {
		return false, err
	}
	return !isManual, nil
}

// hasMarker checks if the file at path contains the auto-generated marker.
// It scans the file line by line using [bufio.Reader] and returns true as soon
// as the marker is found, avoiding reading the entire file.
func hasMarker(path string) (has bool, err error) {
	f, err := os.Open(path)
	if err != nil {
		return false, err
	}
	defer func() {
		if cerr := f.Close(); err == nil {
			err = cerr
		}
	}()

	reader := bufio.NewReader(f)
	for {
		line, rerr := reader.ReadString('\n')
		if strings.Contains(line, autoGeneratedMarker) || strings.Contains(line, autoGeneratedAnnotation) || strings.Contains(line, protobufMarker) || strings.Contains(line, grpcMarker) {
			return true, nil
		}
		if rerr != nil {
			if errors.Is(rerr, io.EOF) {
				break
			}
			return false, rerr
		}
	}
	return false, nil
}
